version: '3'

services:
  db:
    image: postgres
    container_name: db_graphql
    restart: always
    networks:
      - graphql-networks
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=graphql_db
    volumes:
      - ./GraphQL/pgdata:/data/postgres

  app:
    build:
      context: ./GraphQL
    container_name: app_graphql
    entrypoint: dockerize --wait tcp://db_graphql:5432 --timeout 20s docker-entrypoint.sh
    networks:
      - graphql-networks
    volumes:
      - ./GraphQL:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: npm run dev
    ports:
      - 3000:4000
    depends_on:
      - db


networks:
  graphql-networks:
    driver: bridge